blueprint:
  name: deConz - IKEA somrig
  description: Control anything using IKEA somrig
  source_url: https://github.com/noud-github/ha-blueprints/ikea-somrig/deconz-ikea-somrig-switch.yaml
  domain: automation
  input:
    remote:
      name: switch
      description: IKEA Somrig
      selector:
        device:
          integration: deconz
          manufacturer: IKEA of Sweden
          model: SOMRIG shortcut button
    button_shortcut_one:
      name: Shortcut One button press
      description: Action to run on button press
      default: []
      selector:
        action: {}
    button_shortcut_one_sr:
      name: Shortcut One button short release
      description: Action to run on button press
      default: []
      selector:
        action: {}
    button_shortcut_one_lr:
      name: Shortcut One button long release
      description: Action to run on button press
      default: []
      selector:
        action: {}
    button_shortcut_one_double:
      name: Shortcut One button double press
      description: Action to run on button press
      default: []
      selector:
        action: {}
    button_shortcut_two:
      name: Shortcut Two button press
      description: Action to run on button press
      default: []
      selector:
        action: {}
    button_shortcut_two_sr:
      name: Shortcut Two button short release
      description: Action to run on button press
      default: []
      selector:
        action: {}
    button_shortcut_two_lr:
      name: Shortcut Two Button long release
      description: Action to run on button press
      default: []
      selector:
        action: {}
    button_shortcut_two_double:
      name: Shortcut Two Button double press
      description: Action to run on button press
      default: []
      selector:
        action: {}  
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input "remote"
action:
  - variables:
      event: "{{ trigger.event.data.event }}"
  - choose:
      - conditions:
          - "{{ event == 1001 }}"
        sequence: !input "button_shortcut_one_sr"
      - conditions:
          - "{{ event == 1002 }}"
        sequence: !input "button_shortcut_one"
      - conditions:
          - "{{ event == 1003 }}"
        sequence: !input "button_shortcut_one_lr"
      - conditions:
          - "{{ event == 1004 }}"
        sequence: !input "button_shortcut_one_double"
      - conditions:
          - "{{ event == 2001 }}"
        sequence: !input "button_shortcut_two_sr"
      - conditions:
          - "{{ event == 2002 }}"
        sequence: !input "button_shortcut_two"
      - conditions:
          - "{{ event == 2003 }}"
        sequence: !input "button_shortcut_two_lr"
      - conditions:
          - "{{ event == 2004 }}"
        sequence: !input "button_shortcut_two_double"
     
     